  # Build the container image
  - name: 'gcr.io/cloud-builders/docker:latest'
    id: 'build-image'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/crops-prices-app-${_ENV}',
      '--build-arg', 'APP_ENV=${_ENV}',
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker:latest'
    id: 'push-image'
    waitFor: ['build-image']
    args: ['push', 'gcr.io/$PROJECT_ID/crops-prices-app-${_ENV}']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    id: 'deploy-to-cloud-run'
    waitFor: ['push-image']
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'crops-prices-app-${_ENV}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/crops-prices-app-${_ENV}'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'APP_ENV=${_ENV}'

substitutions:
  _ENV: 'staging'  # default value

images:
  - 'gcr.io/$PROJECT_ID/crops-prices-app-${_ENV}'