#!/usr/bin/env python3
"""Generate the frontend whitelist of well-populated products and markets.

Reads the manifest and availability CSVs, applies thresholds, and writes
frontend/src/lib/whitelist.ts with hardcoded Sets keyed as "name|unit|origin".

Thresholds:
  - Products: >=100 weeks of data
  - Markets: >=3000 total data points across all products
"""

import csv
import json
from collections import defaultdict
from pathlib import Path

DATA_DIR = Path("public/data")
AVAIL_DIR = Path("data/availability")
OUT = Path("frontend/src/lib/whitelist.ts")

PRODUCT_MIN_WEEKS = 100
MARKET_MIN_POINTS = 3000


def normalize_for_filename(name: str, unit: str) -> str:
    """Replicate the filename normalization from generate_availability.py."""
    safe_name = name.replace("/", "-").replace(" ", "_").replace(":", "")
    return f"{safe_name}_{unit}"


def main():
    manifest = json.load(open(DATA_DIR / "manifest.json"))
    all_markets = sorted(manifest["places"])

    # Count weeks per product and data points per market
    product_weeks: dict[str, int] = defaultdict(int)
    market_points: dict[str, int] = defaultdict(int)

    for product in manifest["products"]:
        stem = normalize_for_filename(product["name"], product["unit"])
        csv_path = AVAIL_DIR / product["category"] / product["origin"] / f"{stem}.csv"

        key = f"{product['name']}|{product['unit']}|{product['origin']}"

        if not csv_path.exists():
            product_weeks[key] = 0
            continue

        with open(csv_path) as f:
            reader = csv.reader(f)
            header = next(reader)
            markets = header[1:]
            rows = list(reader)

        product_weeks[key] += len(rows)
        for row in rows:
            for i, cell in enumerate(row[1:]):
                if i < len(markets) and cell.strip() == "X":
                    market_points[markets[i]] += 1

    # Apply thresholds
    whitelisted_products = sorted(
        name for name, weeks in product_weeks.items() if weeks >= PRODUCT_MIN_WEEKS
    )
    whitelisted_markets = sorted(
        name for name, points in market_points.items() if points >= MARKET_MIN_POINTS
    )

    # Write whitelist.ts
    products_str = "\n".join(f'  "{p}",' for p in whitelisted_products)
    markets_str = "\n".join(f'  "{m}",' for m in whitelisted_markets)

    content = f"""\
// Auto-generated by scripts/generate_whitelist.py — do not edit manually.
// Products with >={PRODUCT_MIN_WEEKS} weeks of data across all years.
export const WHITELISTED_PRODUCTS = new Set([
{products_str}
]);

// Markets with >={MARKET_MIN_POINTS} total data points across all products.
export const WHITELISTED_MARKETS = new Set([
{markets_str}
]);
"""
    OUT.write_text(content)
    print(f"Wrote {OUT}")
    print(f"  Products: {len(whitelisted_products)} whitelisted (of {len(product_weeks)} total)")
    print(f"  Markets:  {len(whitelisted_markets)} whitelisted (of {len(market_points)} total)")


if __name__ == "__main__":
    main()
